---
ID: "7e3dfdc1-aed2-4f28-bc5a-aa1c2c44518c"
Parent: "040e0a8b-0b4b-4ac6-bafe-3ece65b6dbce"
Template: "040e0a8b-0b4b-4ac6-bafe-3ece65b6dbce"
Path: /sitecore/templates/Project/SiteRoot/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220811T125457Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
