---
ID: "cf858db9-4e83-4520-b948-f5391f63ca11"
Parent: "548b3039-230e-4458-bfa8-96381032aa27"
Template: "548b3039-230e-4458-bfa8-96381032aa27"
Path: /sitecore/templates/Project/Page Templates/Base Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{6B1A24DB-7358-4FEB-B068-CD17B7632A57}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220811T205551Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "f8ceef87-756e-4fed-9393-a7ae73c5f8ae"
      Hint: Title
      Value: $name
