---
ID: "95419180-5510-4951-a3ed-41042dfa2070"
Parent: "8dd103c3-4b58-4791-92be-cda900d97730"
Template: "8dd103c3-4b58-4791-92be-cda900d97730"
Path: /sitecore/templates/Project/Body Controls/Royal Cars/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220905T124325Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
